### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by ericgaspar**

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by lapineige** [comment]
Current dev branch is : https://github.com/YunoHost-Apps/bonfire_ynh/pull/5

**Comment by ericgaspar** [comment]
Why is this branch deleted? Isn't the point of opening a branch to work on the project and not interfere with your branch?

**Comment by lapineige** [comment]
Sorry that was a bit hasty and harsh.
I took a look at the branch and it wasn't using the latest version (while updating it) and there is already some big troubles in #5 (which is pointing to testing, as this one) so I thought it wasn't useful to split the effort with another branch which seemed (maybe I didn't get the point of this branch) to mainly and only update the version and small formatting stuff.

Also I didn't delete this branch.

**Pull request closed without merging**
