### PR TITLE
update release & script, and move admin creation before daemon

### PR DESCRIPTION
**Pull request by mayel**

### CODE REVIEW

**Comment by mayel** [comment]
hold on, moving the admin creation means it doesn't have .env loaded, working on that

**Comment by mayel** [comment]
@lapineige can we test this?

**Comment by lapineige** [comment]
!testme

**Comment by mayel** [comment]
hmm, so maybe the environment of the install script is not shared with the app when run by `ynh_exec_warn_less`

**Comment by mayel** [comment]
the reason I moved it to before the daemon (and using `eval` which starts the app, instead of `rpc` which tries to connect to an already running app) is that otherwise without some way to know the app has finished starting and is in a ready state the user creation may fail to early

**Comment by lapineige** [comment]
> otherwise without some way to know the app has finished starting and is in a ready state the user creation may fail to early

The start command config should be there to wait any "I finished starting" line. Waiting for that log : https://github.com/bonfire-networks/bonfire-yunohost/blob/use-release/scripts/install#L126

**Comment by mayel** [comment]
aha!

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
Same errors apparently.
These messages are quite confusing for me :(

**Comment by lapineige** [comment]
Could you update to latest release https://github.com/bonfire-networks/bonfire-app/releases/tag/v0.9.10-beta.75 ?
I can't edit the branch myself.

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
Already a new release in the meantime :sweat_smile:
Is that necessary for the adsf just issue ?

**Pull request merged**
