### PR TITLE
Update to 0.9.10-beta.36

### PR DESCRIPTION
**Pull request by mayel**
testing a PR

### CODE REVIEW

**Comment by mayel** [comment]
!testme

**Comment by mayel** [comment]
@lapineige could we try running this in CI? locally it's getting stuck on a JS error now...

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
Thank you for that work :)

**Comment by lapineige** [comment]
From the detailed logs:  https://ci-apps-dev.yunohost.org/ci/logs/15049.log

```
779867 [37m[1mDEBUG [m$ NODE_PATH=./node_modules:../../../deps/bonfire_editor_milkdown/assets/node_modules npx esbuild ./js/bonfire_live.js ./js/bonfire_basic.js --target=es2017 --bundle --sourcemap --loader:.svg=text --bundle --outdir=../../../priv/static/assets

780430 [37m[1mDEBUG [mâœ˜ [ERROR] Could not resolve "../../../../data/current_flavour/config/flavour_assets/hooks/Bonfire.UI.Common.PreviewContentLive.hooks"

780430 [37m[1mDEBUG [m

780431 [37m[1mDEBUG [m    js/bonfire_basic.js:9:20:

780431 [37m[1mDEBUG [m      9 â”‚ ...as c1 from "../../../../data/current_flavour/config/flavour_asse...

780432 [37m[1mDEBUG [m        â•µ               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

780432 [37m[1mDEBUG [m

780473 [37m[1mDEBUG [m1 error

780479 [37m[1mDEBUG [mnode:child_process:929

780480 [37m[1mDEBUG [m    throw err;

780480 [37m[1mDEBUG [m    ^

780480 [37m[1mDEBUG [m

780480 [37m[1mDEBUG [mError: Command failed: /var/www/bonfire/deps/bonfire_ui_common/assets/node_modules/@esbuild/linux-x64/bin/esbuild ./js/bonfire_live.js ./js/bonfire_basic.js --target=es2017 --bundle --sourcemap --loader:.svg=text --bundle --outdir=../../../priv/static/assets

780480 [37m[1mDEBUG [m    at checkExecSyncError (node:child_process:890:11)

780480 [37m[1mDEBUG [m    at Object.execFileSync (node:child_process:926:15)

780481 [37m[1mDEBUG [m    at Object.<anonymous> (/var/www/bonfire/deps/bonfire_ui_common/assets/node_modules/esbuild/bin/esbuild:221:28)

780481 [37m[1mDEBUG [m    at Module._compile (node:internal/modules/cjs/loader:1364:14)

780481 [37m[1mDEBUG [m    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)

780481 [37m[1mDEBUG [m    at Module.load (node:internal/modules/cjs/loader:1203:32)

780481 [37m[1mDEBUG [m    at Module._load (node:internal/modules/cjs/loader:1019:12)

780481 [37m[1mDEBUG [m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)

780482 [37m[1mDEBUG [m    at node:internal/main/run_main_module:28:49 {

```

**Comment by mayel** [comment]
Yeah that's the same error I saw, which is a weird one since 
1. those JS files are commited in the repo just in case
2. they are usually generated during compilation, which seems to be deleting them but not re-recreating them

This is getting to be frustrating... I'm wondering again why we're doing the build during install instead of in CI? was it just to allow flexibility with flavours/extensions? In which case that's much less needed since implementing https://github.com/bonfire-networks/bonfire-app/issues/910

**Comment by lapineige** [comment]
> I'm wondering again why we're doing the build during install instead of in CI?

We don't have tools to make builds in CI in Yunohost as of now.

> was it just to allow flexibility with flavours/extensions?

That could have been the case, but not. And I'm still wondering how to handle them.
Interesting PR, that might be a game changer for us on packaging side !

**Comment by lapineige** [comment]
What could I do to ease your time testing this / test it for you ?

**Comment by mayel** [comment]
> We don't have tools to make builds in CI in Yunohost as of now.

I mean building an [OTP release in Bonfire's CI](https://github.com/bonfire-networks/bonfire-app/blob/main/.github/workflows/release.yaml#L99) (which is currently disabled) and using the result of that in yunohost instead of building from source

**Comment by mayel** [comment]
That would make it easier to debug and mean we can maintain a single build process (well, besides the docker one) instead of having to maintain custom workarounds here

**Pull request merged**
