### PR TITLE
use release

### PR DESCRIPTION
**Pull request by mayel**
so we can test without the user creation...

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
It seems to work and fail a bit too, I'm merging so I can test it easily and report my findings.

**Comment by lapineige** [comment]
Services dies with : 

```
08:16:20.422 [info] tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Thu, 01 Feb 2024 18:40:48 GMT.
Warning: [os_mon] memory supervisor port (memsup): Erlang has closed
```

**Comment by lapineige** [comment]
If I restart it, no error shown, but I have "Something went wrong" on the web page.

**Comment by lapineige** [comment]
In logs, I have errors like this : 

```
query: "SELECT b0.\"tag_id\", count(b0.\"id\") FROM \"bonfire_tagged\" AS b0 LEFT OUTER JOIN \"pointers_pointer\" AS p1 ON p1.\"id\" = b0.\"tag_id\" WHERE (NOT (p1.\"table_id\" = ANY($1))) AND (b0.\"inserted_at\" >= $2) GROUP BY b0.\"tag_id\" ORDER BY b0.\"count\" DESC LIMIT $3"
  },
  status: 500,
  stack: [
    {Ecto.Adapters.SQL, :raise_sql_call_error, 1,
     [
       file: ~c"lib/ecto/adapters/sql.ex",
       line: 1054,
       error_info: %{module: Exception}
     ]},
    {Ecto.Adapters.SQL, :execute, 6,
     [file: ~c"lib/ecto/adapters/sql.ex", line: 952]},
    {Ecto.Repo.Queryable, :execute, 4,
     [file: ~c"lib/ecto/repo/queryable.ex", line: 232]},
    {Ecto.Repo.Queryable, :all, 3,
     [file: ~c"lib/ecto/repo/queryable.ex", line: 19]},
    {Bonfire.Tag.Tags, :query_list_trending, 2,
     [file: ~c"lib/tags.ex", line: 124]},
    {Bonfire.Common.Cache, :"-do_maybe_apply_cached/4-fun-0-", 6,
     [file: ~c"lib/cache.ex", line: 118]},
    {Cachex, :execute, 3, [file: ~c"lib/cachex.ex", line: 535]},
    {Cachex, :execute!, 2, [file: ~c"lib/cachex.ex", line: 1]}
  ],
  kind: :error,
  layout: {Bonfire.UI.Common.BasicView, "error"},
  flash: %{}
}
    (bonfire_common 0.1.0) lib/utils.ex:143: Bonfire.Common.Utils.current_user/2
    (bonfire_common 0.1.0) lib/utils.ex:284: Bonfire.Common.Utils.current_account/2
    (bonfire_common 0.1.0) lib/utils.ex:269: Bonfire.Common.Utils.current_account/2
    (bonfire_common 0.1.0) lib/config_settings/settings.ex:123: Bonfire.Common.Settings.fetch_all_scopes/2
    (bonfire_common 0.1.0) lib/config_settings/settings.ex:101: Bonfire.Common.Settings.get_merged_ext/2

08:27:38.334 request_id=F8b9VvGIfFVtR2MAAGNR [warning] You should pass a current_user and/or current_account (with settings assoc preloaded) in `opts` depending on what scope of Settings you want for OTP app: :bonfire
    (bonfire_common 0.1.0) lib/config_settings/settings.ex:135: Bonfire.Common.Settings.fetch_all_scopes/2
    (bonfire_common 0.1.0) lib/config_settings/settings.ex:101: Bonfire.Common.Settings.get_merged_ext/2
    (bonfire_common 0.1.0) lib/config_settings/settings.ex:36: Bonfire.Common.Settings.get/3
    (bonfire_ui_common 0.1.0) lib/error/basic_view.ex:69: anonymous fn/2 in Bonfire.UI.Common.BasicView.do_render/2
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/engine.ex:150: Phoenix.HTML.Safe.Phoenix.LiveView.Rendered.to_iodata/1

08:27:38.336 request_id=F8b9VvGIfFVtR2MAAGNR [info] Sent 500 in 213ms
08:27:44.257 [error] The `oban_peers` table is undefined and leadership is disabled.

Run migrations up to v11 to restore peer leadership. In the meantime, distributed plugins
(e.g. Cron, Pruner) will not run on any nodes.

```

**Comment by mayel** [comment]
> Services dies with :
> 
> ```
> 08:16:20.422 [info] tzdata release
> ```

interesting, happening even with a different tz library... no actual error message though?

> In logs, I have errors like this...

Seems like maybe migrations are not running correctly. They usually run automatically on startup and output something like this (or an error): 
Screenshot 2024-04-17 at 09 34 09

Otherwise can you try running them from iex? `EctoSparkles.AutoMigrator.startup_migrations`

**Comment by lapineige** [comment]
`EctoSparkles.AutoMigrator.startup_migrations`
I'm unsure how to run this… I'll try

**Comment by lapineige** [comment]
`yunohost app shell bonfire` and `./bin/bonfire eval 'EctoSparkles.AutoMigrator.startup_migrations'`
I did it, apparently it worked.

Then I started the server (`./bin/bonfire start`), and :

```
21:27:35.368 [info] Child Oban.Queue.Watchman of Supervisor {Oban.Registry, {Oban, {:queue, "database_prune"}}} started
Pid: #PID<0.8088.0>
Start Call: Oban.Queue.Watchman.start_link([foreman: {:via, Registry, {Oban.Registry, {Oban, {:foreman, "database_prune"}}}}, name: {:via, Registry, {Oban.Registry, {Oban, {:watchman, "database_prune"}}}}, producer: {:via, Registry, {Oban.Registry, {Oban, {:producer, "database_prune"}}}}, shutdown: 15000])
21:27:35.364 [error] Child Oban.Queue.Producer of Supervisor {Oban.Registry, {Oban, {:queue, "deletion"}}} terminated
** (exit) an exception was raised:
    ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "public.oban_jobs" does not exist

    query: WITH "subset" AS MATERIALIZED(SELECT so0."id" AS "id" FROM "public"."oban_jobs" AS so0 WHERE (so0."state" = 'available') AND (so0."queue" = $1) ORDER BY so0."priority", so0."scheduled_at", so0."id" LIMIT $2 FOR UPDATE SKIP LOCKED) UPDATE "public"."oban_jobs" AS o0 SET "state" = $3, "attempted_at" = $4, "attempted_by" = $5, "attempt" = o0."attempt" + $6 FROM "subset" AS f1 WHERE (o0."id" = f1."id") AND (o0."attempt" < o0."max_attempts") RETURNING o0."id", o0."state", o0."queue", o0."worker", o0."args", o0."meta", o0."tags", o0."errors", o0."attempt", o0."attempted_by", o0."max_attempts", o0."priority", o0."attempted_at", o0."cancelled_at", o0."completed_at", o0."discarded_at", o0."inserted_at", o0."scheduled_at"
        (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
        (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
        (ecto 3.11.2) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
        (oban 2.17.8) lib/oban/engines/basic.ex:119: anonymous fn/4 in Oban.Engines.Basic.fetch_jobs/3
        (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1358: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
        (db_connection 2.6.0) lib/db_connection.ex:1710: DBConnection.run_transaction/4
        (oban 2.17.8) lib/oban/engine.ex:223: anonymous fn/4 in Oban.Engine.fetch_jobs/3
        (oban 2.17.8) lib/oban/engine.ex:319: anonymous fn/3 in Oban.Engine.with_span/4
Pid: #PID<0.8050.0>
Start Call: Oban.Queue.Producer.start_link([dispatch_cooldown: 5, queue: "deletion", conf: %Oban.Config{dispatch_cooldown: 5, engine: Oban.Engines.Basic, get_dynamic_repo: nil, insert_trigger: false, log: false, name: Oban, node: "bonfire@social", notifier: {Oban.Notifiers.Postgres, []}, peer: {Oban.Peers.Postgres, []}, plugins: [{Oban.Plugins.Cron, [crontab: [{"*/10 * * * *", Bonfire.UI.Common.StaticGenerator, [max_attempts: 3]}, {"@daily", ActivityPub.Pruner.PruneDatabaseWorker, [max_attempts: 1]}, {"@hourly", Bonfire.OpenScience.APIs}]]}, {Oban.Plugins.Lifeline, [rescue_after: 3600000]}, {Oban.Plugins.Pruner, [max_age: 604800]}], prefix: "public", queues: [federator_incoming: [limit: 5], federator_outgoing: [limit: 5], remote_fetcher: [limit: 3], import: [limit: 1], deletion: [limit: 1], database_prune: [limit: 1], static_generator: [limit: 1], fetch_open_science: [limit: 1]], repo: Bonfire.Common.Repo, shutdown_grace_period: 15000, stage_interval: 2000, testing: :disabled}, limit: 1, foreman: {:via, Registry, {Oban.Registry, {Oban, {:foreman, "deletion"}}}}, name: {:via, Registry, {Oban.Registry, {Oban, {:producer, "deletion"}}}}])
```

And a bunch of "non warning" message are shown every 2s.

**Pull request merged**
