### PR TITLE
Use precompiled release

### PR DESCRIPTION
**Pull request by mayel**

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
It's failing because postgresql install (and yarn and elixir) are disabled O_o
Is there a specific reason for you to do that @mayel :thinking:

**Comment by lapineige** [comment]
Can you cancel those comments ?

**Comment by mayel** [comment]
Elixir is installed in the `deps-debian.sh` script and yarn shouldn't be needed anymore since we're not building, but I didn't mean to disable postgres!

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
Debian 11 CI seems buggy.

In Debian 12 (your changes might have fixed it !):

```
328106 INFO    DEBUG - + sudo -u bonfire -s /bin/bash -lc 'WITH_DOCKER=no just cmd /var/www/bonfire/bin/bonfire rpc '\''Bonfire.Me.make_account_and_user("package_checker", "", "**********")'\'''
328107 INFO    DEBUG - /bin/bash: line 1: just: command not found
```

**Comment by mayel** [comment]
Ah it should be something like `ExecStart=__INSTALL_DIR__/bin/bonfire start daemon` instead of still using just

**Comment by lapineige** [comment]
I can't commit that change on your branch. Would you mind changing it ?

**Comment by mayel** [comment]
Done

**Comment by mayel** [comment]
(such a ridiculous UX choice by GitHub btw)

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
```
325973 WARNING =INFO REPORT==== 16-Apr-2024::18:11:55.068136 ===
325973 WARNING     application: kernel
325973 WARNING     exited: {{shutdown,
325973 WARNING                  {failed_to_start_child,on_load,
325973 WARNING                      {on_load_function_failed,crypto,
325973 WARNING                          {error,
325973 WARNING                              {load_failed,
325974 WARNING                                  "Failed to load NIF library /var/www/bonfire/lib/crypto-5.4.2/priv/lib/crypto: 'libcrypto.so.1.1: cannot open shared object file: No such file or directory'"}}}}},
325974 WARNING              {kernel,start,[normal,[]]}}
325974 WARNING     type: permanent
325974 WARNING Kernel pid terminated (application_controller) ("{application_start_failure,kernel,{{shutdown,{failed_to_start_child,on_load,{on_load_function_failed,crypto,{error,{load_failed,\"Failed to load NIF library /var/www/bonfire/lib/crypto-5.4.2/priv/lib/crypto: 'libcrypto.so.1.1: cannot open shared object file: No such file or directory'\"}}}}},{kernel,start,[normal,[]]}}}")
```

So we're missing a library ? :thinking:

**Comment by lapineige** [comment]
Interesting, that's not the case in Debian 12 : https://ci-apps-dev.yunohost.org/ci/job/15077

But there is another error: 
```
338943 WARNING WARNING: The environment variable MAIL_BACKEND was not set or was set incorrectly, mail will NOT be sent.
338945 WARNING ERROR! Config provider Config.Reader failed with:
338945 WARNING ** (RuntimeError) Environment variables for database are missing.
338945 WARNING For example: DATABASE_URL=ecto://USER:PASS@HOST/DATABASE
338945 WARNING You can also set POSTGRES_PASSWORD (required),
338946 WARNING and POSTGRES_USER (default: postgres) and POSTGRES_HOST (default: localhost)
```

**Comment by mayel** [comment]
Progress! 😄 May need to install OpenSSL and some other libraries, I'll check what we install in docker...

**Comment by mayel** [comment]
I guess Debian 12 may have that lib installed by default, but the DB error is strange. Maybe the env file isn't being used correctly?

**Comment by lapineige** [comment]
I guess so, but I can't find the issue :thinking:

**Comment by mayel** [comment]
But is that loaded into the systemd's environment somehow? Just used to do it for us, but maybe there's a simpler way

**Comment by lapineige** [comment]
Well it's in the working directory https://github.com/bonfire-networks/bonfire-yunohost/blob/use-release/conf/systemd.service#L9 and readable :thinking:

**Comment by mayel** [comment]
Aha something like this? https://github.com/YunoHost-Apps/funkwhale_ynh/blob/a4a126a0fa01b437086d14700b850ae1c175109c/conf/funkwhale-server.service#L10

**Comment by lapineige** [comment]
I didn't know this one :-o
Well done !

**Comment by lapineige** [comment]
!testme

**Comment by mayel** [comment]
So I'm not sure what I'm reading, it says it didn't start before the timeout but there's also logs of it starting?

**Comment by mayel** [comment]
ah there may be more info in `/var/log/bonfire/bonfire.log`

**Comment by lapineige** [comment]
You may need to install it then to watch that folder.
Yunohost doesn't allow me to install from your custom branch, I might merge it (which means another PR will need to be opened) to try it.

**Comment by mayel** [comment]
You can clone it though and do `sudo yunohost app install /dir` (I'm running that now)

**Comment by lapineige** [comment]
I didn't know that ! \o/

**Comment by mayel** [comment]
hmm that log file is empty

**Comment by lapineige** [comment]
You may launch the service manually then ? You can do `yunohost app shell bonfire` to run it in Bonfire user environment.

**Comment by lapineige** [comment]
I have to make a break, I will launch CI again, feel free to restart the job (on the link, click on the restart button) after pushing a commit if you need another run.

**Comment by lapineige** [comment]
!testme

**Comment by mayel** [comment]
hmm strange, even though I removed just: 

```
561707 DEBUG Apr 16 17:21:31 systemd[1]: Started Bonfire daemon.
561712 DEBUG Apr 16 17:21:32 systemd[31606]: bonfire.service: Failed to locate executable just: No such file or directory
561719 DEBUG Apr 16 17:21:32 systemd[31606]: bonfire.service: Failed at step EXEC spawning just: No such file or directory
561724 DEBUG Apr 16 17:21:32 systemd[1]: bonfire.service: Main process exited, code=exited, status=203/EXEC
561739 DEBUG Apr 16 17:21:32 systemd[1]: bonfire.service: Failed with result '\''exit-code'\''.
561743 DEBUG Apr 16 20:57:10 systemd[1]: Started Bonfire daemon.
561752 DEBUG Apr 16 20:58:05 systemd[1]: bonfire.service: Main process exited, code=killed, status=4/ILL
561755 DEBUG Apr 16 20:58:05 systemd[1]: bonfire.service: Failed with result '\''signal'\''.
561761 DEBUG Apr 16 20:58:05 systemd[1]: bonfire.service: Consumed 51.457s CPU time.'
```

**Comment by mayel** [comment]
thanks, have a good one!

**Comment by lapineige** [comment]
> hmm strange, even though I removed just:
> 
> ```
> 561707 DEBUG Apr 16 17:21:31 systemd[1]: Started Bonfire daemon.
> 561712 DEBUG Apr 16 17:21:32 systemd[31606]: bonfire.service: Failed to locate executable just: No such file or directory
> 561719 DEBUG Apr 16 17:21:32 systemd[31606]: bonfire.service: Failed at step EXEC spawning just: No such file or directory
> 561724 DEBUG Apr 16 17:21:32 systemd[1]: bonfire.service: Main process exited, code=exited, status=203/EXEC
> 561739 DEBUG Apr 16 17:21:32 systemd[1]: bonfire.service: Failed with result '\''exit-code'\''.
> 561743 DEBUG Apr 16 20:57:10 systemd[1]: Started Bonfire daemon.
> 561752 DEBUG Apr 16 20:58:05 systemd[1]: bonfire.service: Main process exited, code=killed, status=4/ILL
> 561755 DEBUG Apr 16 20:58:05 systemd[1]: bonfire.service: Failed with result '\''signal'\''.
> 561761 DEBUG Apr 16 20:58:05 systemd[1]: bonfire.service: Consumed 51.457s CPU time.'
> ```

But it's still there ? https://github.com/search?q=repo%3Abonfire-networks%2Fbonfire-yunohost+just&type=code

**Comment by mayel** [comment]
(wrong branch, though I see it's still in the update script which we can tackle later)

**Comment by mayel** [comment]
I wonder if simply deleting `/etc/yunohost/apps/bonfire` when testing locally before retrying the install leaves some things in place, like the old systemd service and they don't get recreated cleanly

**Comment by lapineige** [comment]
Yes, you should run `yunohost app remove bonfire` to clean it up.

**Comment by mayel** [comment]
hmm ok, even without seeing more detailed logs, we can see that it tries to start several times and the last output before that is `[info] Tz download done` so it may well be the same issue as in https://github.com/mathieuprog/tz/issues/25

**Review by lapineige — APPROVED** [review]

**Comment by lapineige** [comment]
Merging as it is already a big improvement, and stuck with the same issue apparently.
I'll test it then.

**Pull request merged**
